sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
install:
  - npm install
script:
  - make test-coveralls
notifications:
  email:
    recipients:
      - ccharlieli@live.com
    on_success: never
    on_failure: always
    